create schema ESTUDODECASO4;
use ESTUDODECASO4;

create table if not exists ALUNOS(
ALU_CPF INT PRIMARY KEY,
ALU_NOME VARCHAR(45) NOT NULL,
ALU_RUA VARCHAR(45) NOT NULL,
ALU_NUMRUA INT,
ALU_BAIRRO VARCHAR(45) NOT NULL,
ALU_CIDADE VARCHAR(45) NOT NULL,
ALU_ESTADO VARCHAR(45) NOT NULL,
ALU_PAIS VARCHAR(30) NOT NULL,
ALU_CODPOSTAL VARCHAR(10) NOT NULL,
ALU_TELEFONE VARCHAR(15) NOT NULL,
ALU_EMAIL VARCHAR(100) NOT NULL,
ALU_MODALIDADE INT NOT NULL
);

