create schema ESTUDODECASO3;
use ESTUDODECASO3;

create table if not exists CLIENTES(
CLI_ID INT primary key,
CLI_CNPJ VARCHAR(14) NOT NULL,
CLI_RAZAO_SOCIAL VARCHAR(100) NOT NULL,
CLI_RAMO_ATIVIDADE TEXT NOT NULL,
CLI_DATA_CADASTRO DATE NOT NULL
);

create table if not exists FORNECEDORES(
FORN_CNPJ VARCHAR(14) primary key,
FORN_RAZAO_SOCIAL VARCHAR(100) NOT NULL
);

create table if not exists TIPO_COMPONENTES(
TC_ID INT primary key,
TC_NOME VARCHAR(50) NOT NULL
);

create table if not exists COMPONENTES(
COMP_ID INT primary key,
COMP_TIPO VARCHAR(50) NOT NULL,
COMP_NOME VARCHAR(50) NOT NULL,
COMP_QUANTIDADE_ESTOQUE INT NOT NULL,
COMP_PREÇO_UNIDADE DECIMAL(10,3) NOT NULL,
COMP_UNIDADE INT NOT NULL
);

create table if not exists MAQUINAS(
MAQ_ID INT primary key,
MAQ_TEMPO_VIDA VARCHAR(50) NOT NULL,
MAQ_DATA_COMPRA DATE NOT NULL,
MAQ_DATA_FIM_GARANTIA DATE NOT NULL
);

create table if not exists RECURSOS_ESPECIFICOS(
RE_ID INT primary key,
RE_QUANTIDADE_NECESSARIA INT NOT NULL,
RE_UNIDADE INT NOT NULL,
RE_TEMPO_USO DECIMAL (10,1) NOT NULL,
RE_HORAS_MAO_OBRA DECIMAL (10,2) NOT NULL
);

create table if not exists CARGOS(
CAR_ID INT primary key,
CAR_NOME VARCHAR(50) NOT NULL
);

create table if not exists FUNCOES(
FUN_ID INT primary key,
FUN_NOME VARCHAR(50) NOT NULL
);

create table if not exists ENCOMENDAS(
ENC_ID INT,
ENC_DATA_INCLUSAO DATE NOT NULL,
ENC_VALOR_TOTAL DECIMAL(10,2) NOT NULL,
ENC_VALOR_DESCONTO DECIMAL(10,2) NOT NULL,
ENC_VALOR_LIQUIDO DECIMAL(10,2) NOT NULL,
ENC_QTD_PARCELAS INT,
ENC_CLIENTES INT,
primary key (ENC_ID, ENC_CLIENTES),
constraint FK_CLIENTE_ENC foreign key (ENC_CLIENTES)
references CLIENTES(CLI_ID)
);

create table if not exists PRODUTOS(
PROD_ID INT,
PROD_RE INT,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_COR VARCHAR(50) NOT NULL,
PROD_DIMESOES VARCHAR(50) NOT NULL,
PROD_PESO VARCHAR(50) NOT NULL,
PROD_PREÇO DECIMAL(10,2) NOT NULL,
PROD_TEMPO_FAB VARCHAR(50) NOT NULL,
PROD_DESENHO BLOB NOT NULL, 
#SE FOR UMA URL É VARCHAR(255), BLOB É PARA IMAGEM DENTRO DO BANCO DE DADOS, MAS AUMENTA O TAMANHO DO BD PELO QUE EU PESQUISEI
PROD_HORAS_MAO_OBRA VARCHAR(50) NOT NULL,
primary key (PROD_ID, PROD_RE),
constraint FK_RECURSOS_ESPECIFICOS_PROD foreign key (PROD_RE)
references RECURSOS_ESPECIFICOS(RE_ID)
);

create table if not exists PAGAMENTOS(
PAG_ID INT,
PAG_CLIENTE INT,
PAG_ENCOMENDA INT,
primary key (PAG_ID, PAG_CLIENTE, PAG_ENCOMENDA),
PAG_TIPO_FORMA VARCHAR(50) NOT NULL,
PAG_VALOR_TOTAL DECIMAL(10,2),
constraint FK_CLIENTE_PAG foreign key (PAG_CLIENTE)
references CLIENTES(CLI_ID),
constraint FK_ENCOMENDA_PAG foreign key (PAG_ENCOMENDA)
references ENCOMENDAS(ENC_ID)
);

create table if not exists REGISTRO_MANUTENCAO(
RM_MAQUINA INT primary key,
RM_DATA DATE NOT NULL,
RM_DESCRICAO VARCHAR(100) NOT NULL,
constraint FK_MAQUINA_RM foreign key(RM_MAQUINA)
references MAQUINAS(MAQ_ID)
);

create table if not exists REGISTRO_SUPRIMENTOS(
RS_PRODUTO INT primary key,
RS_QUANTIDADE INT NOT NULL,
RS_DATA_NECESSIDADE DATE NOT NULL,
constraint FK_PRODUTOS_RS foreign key(RS_PRODUTO)
references PRODUTOS(PROD_ID)
);

create table if not exists PESSOA_CONTATO(
PC_ID INT,
PC_CLIENTE INT,
PC_FORNECEDOR VARCHAR(14),
PC_NOME VARCHAR(50) NOT NULL,
primary key (PC_ID, PC_CLIENTE, PC_FORNECEDOR),
constraint FK_CLIENTE_PC foreign key(PC_CLIENTE)
references CLIENTES(CLI_ID),
constraint FK_FORNECEDOR_PC foreign key(PC_FORNECEDOR)
references FORNECEDORES(FORN_CNPJ) 
);

create table if not exists CARGOS_FUNCOES(
CF_CARGO INT,
CF_FUNCAO INT,
primary key (CF_CARGO, CF_FUNCAO),
constraint PKFK_CARGO_CF foreign key(CF_CARGO)
references CARGOS(CAR_ID),
constraint PKFK_FUNCAO_CF foreign key(CF_FUNCAO)
references FUNCOES(FUN_ID)
);

create table if not exists EMPREGADOS( 
EMP_ID INT,
EMP_FUN INT,
EMP_CAR INT,
primary key (EMP_ID, EMP_FUN, EMP_CAR),
EMP_NOME VARCHAR(50) NOT NULL,
EMP_SALARIO DECIMAL(10,2) NOT NULL,
EMP_DATA_ADMISSAO DATE NOT NULL,
EMP_QUALIFICACOES VARCHAR(50) NOT NULL,
constraint FK_CAR_FUN_EMP foreign key(EMP_CAR, EMP_FUN)
references CARGOS_FUNCOES(CF_CARGO, CF_FUNCAO)
);

create table if not exists TELEFONES(
TELE_CLIENTE INT,
TELE_EMPREGADO INT,
TELE_FORNECEDOR VARCHAR(14),
TELE_NUMERO VARCHAR(20) NOT NULL,
primary key(TELE_CLIENTE, TELE_EMPREGADO, TELE_FORNECEDOR),
constraint FK_CLIENTE_TELE foreign key(TELE_CLIENTE)
references CLIENTES(CLI_ID),
constraint FK_EMPREGADO_TELE foreign key(TELE_EMPREGADO)
references EMPREGADOS(EMP_ID),
constraint FK_FORNECEDOR_TELE foreign key(TELE_FORNECEDOR)
references FORNECEDORES(FORN_CNPJ)
);

create table if not exists ENDERECOS(
ENDE_CLIENTE INT,
ENDE_EMPREGADO INT,
ENDE_FORNECEDOR VARCHAR(14),
primary key(ENDE_CLIENTE, ENDE_EMPREGADO, ENDE_FORNECEDOR),
ENDE_TIPO VARCHAR(45) NOT NULL,
ENDE_NUMERO INT,
ENDE_LOGRADOURO VARCHAR(45) NOT NULL,
ENDE_CEP VARCHAR(10) NOT NULL,
ENDE_COMPLEMENTO VARCHAR(45) NOT NULL,
ENDE_BAIRRO VARCHAR(45) NOT NULL,
ENDE_CIDADE VARCHAR(45) NOT NULL,
ENDE_ESTADO VARCHAR(45) NOT NULL,
ENDE_PAIS VARCHAR(45) NOT NULL,
constraint FK_CLIENTE_ENDE foreign key(ENDE_CLIENTE)
references CLIENTES(CLI_ID),
constraint FK_EMPREGADO_ENDE foreign key(ENDE_EMPREGADO)
references EMPREGADOS(EMP_ID),
constraint FK_FORNECEDOR_ENDE foreign key(ENDE_FORNECEDOR)
references FORNECEDORES(FORN_CNPJ)
);

create table if not exists PRODUTOS_EMPREGADOS(
PREM_EMPREGADO INT,
PREM_PRODUTO INT,
primary key(PREM_EMPREGADO, PREM_PRODUTO),
constraint PKFK_PRODUTO_PREM foreign key(PREM_PRODUTO)
references PRODUTOS(PROD_ID),
constraint PKFK_EMPREGADO_PREM foreign key(PREM_EMPREGADO)
references EMPREGADOS(EMP_ID)
);

create table if not exists FORNECEDOR_COMPONENTE(
FOCO_FORNECEDOR VARCHAR(14),
FOCO_COMPONENTE INT,
primary key (FOCO_FORNECEDOR, FOCO_COMPONENTE),
constraint FK_FORNECEDOR_FOCO foreign key(FOCO_FORNECEDOR)
references FORNECEDORES(FORN_CNPJ),
constraint FK_COMPONENTE_FOCO foreign key(FOCO_COMPONENTE)
references COMPONENTES(COMP_ID)
);

create table if not exists PRODUTOS_ENCOMENDA(
PREN_PRODUTO INT,
PREN_ENCOMENDA INT,
primary key (PREN_PRODUTO, PREN_ENCOMENDA),
constraint FK_PRODUTO_PREN foreign key(PREN_PRODUTO)
references PRODUTOS(PROD_ID),
constraint FK_ENCOMENDA_PREN foreign key(PREN_ENCOMENDA)
references ENCOMENDAS(ENC_ID)
);

create table if not exists PRODUTOS_MAQUINA(
PRMA_PRODUTO INT,
PRMA_MAQUINA INT,
primary key (PRMA_PRODUTO, PRMA_MAQUINA),
constraint FK_PRODUTO_PRMA foreign key(PRMA_PRODUTO)
references PRODUTOS(PROD_ID),
constraint FK_MAQUINA_PRMA foreign key(PRMA_MAQUINA)
references MAQUINAS(MAQ_ID)
);

create table if not exists PRODUTOS_TIPO_COMPONENTE(
PRTC_PRODUTO INT,
PRTC_TC INT,
primary key(PRTC_PRODUTO, PRTC_TC),
constraint FK_PRODUTO_PRTC foreign key(PRTC_PRODUTO)
references PRODUTOS(PROD_ID),
constraint FK_TIPO_COMPONENTE_PRTC foreign key(PRTC_TC)
references TIPO_COMPONENTES(TC_ID)
);

#Exemplo de Alters
alter table CLIENTES modify column CLI_RAZAO_SOCIAL VARCHAR(200) NOT NULL;
alter table FORNECEDORES modify column FORN_RAZAO_SOCIAL VARCHAR(200) NOT NULL;
alter table TIPO_COMPONENTES modify column TC_NOME VARCHAR(100) NOT NULL;
alter table COMPONENTES modify column COMP_NOME VARCHAR(100) NOT NULL;
alter table MAQUINAS modify column MAQ_TEMPO_VIDA VARCHAR(100) NOT NULL;
alter table RECURSOS_ESPECIFICOS modify column RE_TEMPO_USO DECIMAL (10,2) NOT NULL;
alter table CARGOS modify column CAR_NOME VARCHAR(100) NOT NULL;
alter table FUNCOES modify column FUN_NOME VARCHAR(100) NOT NULL;
alter table ENCOMENDAS modify column ENC_QTD_PARCELAS VARCHAR(4);
alter table PRODUTOS modify column PROD_NOME VARCHAR(100) NOT NULL;
alter table PAGAMENTOS modify column PAG_TIPO_FORMA VARCHAR(55) NOT NULL;
alter table REGISTRO_MANUTENÇÃO modify column RM_DESCRICAO VARCHAR(200) NOT NULL;
alter table REGISTRO_SUPRIMENTOS add ABC INT;
alter table REGISTRO_SUPRIMENTOS drop column ABC;
alter table PESSOA_CONTATO modify column PC_NOME VARCHAR(100) NOT NULL;
alter table CARGOS_FUNCOES add ABC INT;
alter table CARGOS_FUNCOES drop column ABC;
alter table EMPREGADOS modify column EMP_NOME VARCHAR(100) NOT NULL;
alter table TELEFONES add ABC INT;
alter table TELEFONES drop column ABC;
alter table ENDERECOS modify column ENDE_BAIRRO VARCHAR(60) NOT NULL;
alter table PRODUTOS_EMPREGADOS add ABC INT;
alter table PRODUTOS_EMPREGADOS drop column ABC;
alter table FORNECEDOR_COMPONENTE add ABC INT;
alter table FORNECEDOR_COMPONENTE drop column ABC;
alter table PRODUTOS_ENCOMENDA add ABC INT;
alter table PRODUTOS_ENCOMENDA drop column ABC;
alter table PRODUTOS_MAQUINA add ABC INT;
alter table PRODUTOS_MAQUINA drop column ABC;
alter table PRODUTOS_TIPO_COMPONENTE add ABC INT;
alter table PRODUTOS_TIPO_COMPONENTE drop column ABC;

#Drop exemplo
create table if not exists TESTE;
drop table TESTE
