#MY FIRST LITTLE BANK
create schema ECI_CC1M;

#Usando o little bank
use EC1_CC1M;

#Criando a tabela FORNECEDORES
create table if not exists FORNECEDORES(
#NOMEDOATRIBUTO - TIPO - RESTRIÇÃO DE INTEGRIDADE(OPCIONAL)
FORNEC_COD INT primary key,
FORNEC_NOME VARCHAR(45) NOT NULL,
FORNEC_RUA VARCHAR(45) NOT NULL,
FORNEC_NUMRUA INT NOT NULL,
FORNEC_BAIRRO VARCHAR(45) NOT NULL,
FORNEC_CIDADE VARCHAR(45) NOT NULL,
FORNEC_ESTADO VARCHAR(45) NOT NULL,
FORNEC_PAIS VARCHAR(45) NOT NULL,
FORNEC_CODPOSTAL VARCHAR(45) NOT NULL,
FORNEC_TELEFONE VARCHAR(45) NOT NULL,
FORNEC_CONTATO TEXT NOT NULL
);

create table if not exists PRODUTOS(
PROD_COD INT primary key,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_DESCRICAO TEXT NOT NULL,
PROD_ESPECTEC TEXT NOT NULL,
PROD_QUANT DECIMAL(10,3) NOT NULL,
PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
PROD_UNIDADEMEDIDA VARCHAR(10) NOT NULL,
PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);

create table if not exists FILIAIS(
FIL_COD INT primary key,
FIL_NOME VARCHAR(30) NOT NULL,
FIL_RUA VARCHAR(100) NOT NULL,
FIL_NUMRUA INT NOT NULL,
FIL_BAIRRO VARCHAR(50) NOT NULL,
FIL_CIDADE VARCHAR(50) NOT NULL,
FIL_ESTADO VARCHAR(50) NOT NULL,
FIL_PAIS VARCHAR(50) NOT NULL,
FIL_CODPOSTAL VARCHAR(10) NOT NULL,
FIL_CAPACIDADE TEXT NOT NULL
);

#FASE 4: Criar as tabelas com dependência de CHAVE ESTRANGEIRA
#Criando a tebela PEDIDOS
create table if not exists PEDIDOS(
PED_COD INT primary key,
PED_DATA DATE NOT NULL,
PED_HORA TIME NOT NULL,
PED_PREVISAO DATE NOT NULL,
PED_STATUS ENUM('PENDENTE','CONCLUIDO','EM ESPERA') NOT NULL,
PED_FORNECEDOR INT NOT NULL, #Nossa CHAVE ESTRANGEIRA de FORNECEDOR
#Criando a referencia para a CHAVE ESTRANGEIRA
#Restrição apelido CHAVE.ESTRANGEIRA(CAMPO CRIADO) referencia TABELA(CHAVE.PRIMÁRIA)
constraint FK_FORNECEDOR foreign key (PEDIDOS_FORNECEDOR) #DAR NOME A RESTRIÇÃO(CONSTRAINT) É uma BOA PRÁTICA
references FORNECEDORES(FORNEC_COD) #Referencia a CHAVE PRIMÁRIA de FORNECEDORES
);
#Criando a tabela RECEBIMENTOS (Veio depois, pois tem dependência de PEDIDOS)

create table if not exists RECEBIMENTOS(
RECEB_DATA DATE NOT NULL,
RECEB_HORA TIME NOT NULL,
RECEB_QUANT_PROD DECIMAL(10,3) NOT NULL,
RECEB_CONDICAO TEXT NOT NULL,
RECEB_PEDIDOS INT primary key,
constraint FK_PEDIDOS foreign key (RECEB_PEDIDOS) references PEDIDOS(PED_COD)
);

#FASE 5: CRIANDO AS TABELAS ASSOCIATIVAS (ENTIDADES ASSOCIATIVAS)
create table if not exists PEDIDOS_PRODUTOS(
PDPR_PEDIDOS INT,
PDPR_PRODUTO INT,
primary key(PDPR_PEDIDOS,PDPR_PRODUTOS),
PDPR_QUANT decimal(10,3) NOT NULL,
constraint PDPR_PKFK_PEDIDOS foreign key(PDPR_PEDIDOS) references PEDIDOS(PED_COD),
constraint PDPR_PKFK_PRODUTOS foreign key(PDPR_PRODUTOS) references PRODUTOS(PROD_COD)
);

create table if not exists FILIAIS_PRODUTOS(
FLPR_PEDIDOS INT,
FLPR_PRODUTO INT,
primary key(FLPR_FILIAIS,FLPR_PRODUTOS),
FLPR_QUANT decimal(10,3) NOT NULL,
constraint FLPR_FK_FILIAIS foreign key(FLPR_FILIAIS) references FILIAIS(FIL_COD),
constraint FLPR_FK_PRODUTOS foreign key(FLPR_PRODUTOS) references PRODUTOS(PROD_COD)
);

create table if not exists FORNECEDORES_PRODUTOS(
FRPR_PEDIDOS INT,
FRPR_PRODUTO INT,
primary key(FRPR_FORNECEDORES,FRPR_PRODUTOS),
constraint FRPR_FK_FORNECEDORES foreign key(FRPR_FILIAIS) references FORNECEDORES(FORNEC_COD),
constraint FRPR_FK_PRODUTOS foreign key(FRPR_PRODUTOS) references PRODUTOS(PROD_COD)
);