
create schema ESTUDODECASO4;
use ESTUDODECASO4;

create table if not exists ALUNOS(
ALU_ID INT PRIMARY KEY,
ALU_NOME VARCHAR(45) NOT NULL,
ALU_DATA_NASC DATE NOT NULL,
ALU_CPF VARCHAR(11) NOT NULL,
ALU_RUA VARCHAR(45) NOT NULL,
ALU_NUMRUA INT,
ALU_BAIRRO VARCHAR(45) NOT NULL,
ALU_CIDADE VARCHAR(45) NOT NULL,
ALU_ESTADO VARCHAR(45) NOT NULL,
ALU_PAIS VARCHAR(30) NOT NULL,
ALU_CODPOSTAL VARCHAR(10) NOT NULL,
ALU_TELEFONE VARCHAR(15) NOT NULL,
ALU_EMAIL VARCHAR(100) NOT NULL,
ALU_MODALIDADE VARCHAR(20) NOT NULL
);

create table if not exists MODALIDADES(
MOD_ID INT primary key,
MOD_NOME VARCHAR(45) NOT NULL,
MOD_NUMERO_INSCRITOS INT NOT NULL
);

create table if not exists INSTRUTORES(
INS_ID INT primary key,
INS_NOME VARCHAR(45) NOT NULL
);

create table if not exists PAGAMENTOS(
PAG_ID INT primary key,
PAG_DATA DATE NOT NULL,
PAG_VALOR DECIMAL(10,2) NOT NULL,
PAG_STATUS VARCHAR(20) NOT NULL,
PAG_ALUNOS INT NOT NULL,
constraint FK_ALUNOS_PAG foreign key (PAG_ALUNOS)
references ALUNOS(ALU_ID)
);

create table if not exists INSTRUTORES_MODALIDADES(
INMO_INSTRUTORES INT,
INMO_MODALIDADES INT,
primary key(INMO_INSTRUTORES, INMO_MODALIDADES),
constraint PKFK_INSTRUTORES_INMO foreign key(INMO_INSTRUTORES)
references INSTRUTORES(INS_ID),
constraint PKFK_MODALIDADES_INMO foreign key(INMO_MODALIDADES)
references MODALIDADES(MOD_ID)
);

create table if not exists AULAS(
AUL_ID INT,
AUL_INSTRUTOR INT,
AUL_MODALIDADE INT,
primary key(AUL_ID, AUL_INSTRUTOR, AUL_MODALIDADE),
AUL_CAPACIDADE INT NOT NULL,
AUL_HORARIO TIME NOT NULL,
constraint FK_INMO_AUL foreign key(AUL_INSTRUTOR, AUL_MODALIDADE)
references INSTRUTORES_MODALIDADES(INMO_INSTRUTORES, INMO_MODALIDADES)

);

create table if not exists PLANOS_TREINAMENTO(
PLA_ID INT,
PLA_DESCRICAO VARCHAR(200) NOT NULL,
PLA_DATA_CRI DATE NOT NULL,
PLA_DATA_ATU DATE NOT NULL,
PLA_ALUNOS INT,
PLA_INSTRUTOR INT,
PLA_MODALIDADE INT,
primary key (PLA_ALUNOS, PLA_INSTRUTOR, PLA_MODALIDADE, PLA_ID),
constraint FK_INMO_PLA foreign key(PLA_INSTRUTOR, PLA_MODALIDADE)
references INSTRUTORES_MODALIDADES(INMO_INSTRUTORES, INMO_MODALIDADES),
constraint FK_ALUNOS_PLA foreign key(PLA_ALUNOS)
references ALUNOS(ALU_ID)
);

create table if not exists AULAS_ALUNOS(
AUAL_AULAS INT,
AUAL_ALUNOS INT,
primary key (AUAL_AULAS, AUAL_ALUNOS),
constraint PKFK_ALUNOS_AUAL foreign key(AUAL_ALUNOS)
references ALUNOS(ALU_ID),
constraint PKFK_AULAS_AUAL foreign key(AUAL_AULAS)
references AULAS(AUL_ID)
);

#Exemplo de Alters

alter table ALUNOS modify column ALU_NOME VARCHAR(60) NOT NULL;
alter table PAGAMENTOS modify column PAG_STATUS VARCHAR(40) NOT NULL;
alter table MODALIDADES modify column MOD_NOME VARCHAR(50) NOT NULL;
alter table INSTRUTORES modify column INS_NOME VARCHAR(50) NOT NULL;
alter table PLANOS_TREINAMENTO modify column PLA_DESCRICAO VARCHAR(300) NOT NULL;
alter table AULAS add ABC INT;
alter table AULAS drop column ABC;
alter table AULAS_ALUNOS add ABC INT;
alter table AULAS_ALUNOS drop column ABC;
alter table INSTRUTORES_MODALIDADES add ABC INT;
alter table INSTRUTORES_MODALIDADES drop column ABC;

#Exemplo de Drop
create table ABC(
ABC INT
);
drop table ABC